from django.urls import path
from . import views

urlpatterns = [
    path('querytreelist/', views.querytreelist),
    path('queryoneproduct/', views.queryoneproduct),
    path('queryoneplan/', views.queryoneplan),
    path('queryonecase/', views.queryonecase),
    path('treecontrol/', views.treecontrol),
    path('queryDbScheme', views.queryDbScheme),
    path('querydblist/', views.querydblist),
    path('getStepKind/', views.getStepKind),
    path('queryonestep/', views.queryonestep),
    path('queryonebusiness/', views.queryonebusiness),
    path('queryfunclist/', views.queryfunclist),
    path('querydb/', views.querydb),
    path('adddbcon/', views.addcon),
    path('delcon/', views.delcon),
    path('editdbcon/', views.editcon),
    path('copyDbCon/', views.copyDbCon),
    path('editfile/', views.editfile),
    path('addmenu/', views.addmenu),
    path('querywinrm/', views.querywinrm),
    path('queryspacemenu/', views.queryspacemenu),
    path('queryspacefiles/', views.queryspacefiles),
    path('getfiledetail/', views.getfiledetail),
    path('editpathname/', views.editpathname),
    path('delfile/', views.delfile),
    path('checkfilename/', views.checkfilename),
    path('queryonefunc/', views.queryonefunc),
    path('queryfunc', views.queryfunc),
    path('addfunction/', views.addfunc),
    path('delfunc/', views.delfunc),
    path('editfunction/', views.editfunc),
    path('updatefunc/', views.updatefunc),
    path('runplan', views.runtask),
    path('editmailconfig/', views.editmailconfig),
    path('queryonemailconfig/', views.queryonemailconfig),
    path('addtemplate/', views.addtemplate),
    path('deltemplate/', views.deltemplate),
    path('edittemplate/', views.edittemplate),
    path('querytemplate/', views.querytemplate),
    path('querytemplatefield/', views.querytemplatefield),
    path('addtemplatefield/', views.addtemplatefield),
    path('deltemplatefield/', views.deltemplatefield),
    path('edittemplatefield/', views.edittemplatefield),
    path('queryfielddetail/', views.queryfielddetail),
    path('queryUser/', views.queryUser),
    path('queryVars', views.queryVars),
    path('querytaglist/', views.querytaglist),
    path('delVar', views.delVar),
    path('querytags/', views.querytags),
    path('queryVarInSpace',views.queryVarInSpace),
    path('editVarSpaceName',views.editVarSpaceName),
    path('delVarSpace',views.delVarSpace),
    path('addVarSpace',views.addVarSpace),
    path('queryAllVarsInSpace',views.queryAllVarsInSpace),
    path('copyVars',views.copyVars),
    path('queryOneVar', views.queryOneVar),
    path('addVariable', views.addVariable),
    path('editVariable', views.editVariable),
    path('copyvar/', views.copyVar),
    path('testdbcon/', views.testdbcon),
    path('upload/', views.upload),
    path('third_party_call/', views.third_party_call),
    path('editmultivar/', views.editmultivar),
    path('transform/', views.transform),
    path('queryonedb/', views.queryonedb),
    path('queryDbSchemebyVar/', views.queryDbSchemebyVar),
    path('querytag/', views.querytag),
    path('querytemplatecommon/', views.querytemplatecommon),
    path('querytemplatelist/', views.querytemplatelist),
    path('templatefield/', views.templatefield),
    path('downloadfile/', views.downloadfile),
    path('simpletest/', views.simpletest),
    path('querysteptype/', views.querysteptype),
    path('getusernews/', views.getusernews),
    path('getusernewsflag/', views.getusernewsflagstatus),
    path('hasread/', views.hasread),
    path('grab/', views.record),
    path('stoprecord/', views.stoprecord),
    path('queryrecyclelist/', views.queryrecyclelist),
    path('recyclenode/', views.recyclenode),
    path('getTree',views.getTree),
    path('recordBuildNodes',views.recordBuildNodes),
    path('getVars',views.getVars),
    path('editStepKind',views.editStepKind),
    path('queryVarSpace',views.queryVarSpace)
]
