# Generated by Django 2.2.3 on 2020-02-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='menu', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('url', models.TextField()),
                ('description', models.CharField(max_length=64)),
                ('is_allow', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=16)),
                ('kind', models.CharField(max_length=16)),
                ('text', models.CharField(max_length=16)),
                ('url', models.TextField()),
                ('description', models.CharField(max_length=64)),
                ('is_hide', models.BooleanField(default=True)),
                ('is_disable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthWebElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Auth')),
                ('el', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.WebElement')),
            ],
        ),
        migrations.CreateModel(
            name='AuthOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Operation')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Auth')),
            ],
        ),
    ]
