"""
Django settings for ME2 project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import json
from ME2 import configs

BASE_URL = 'http://' + configs.ME2_URL
HELP_DOC_URL = "%s/static/PDF.js/web/viewer.html?file=%s/static/PDF.js/ME2.pdf" % (BASE_URL, BASE_URL)
##Redis配置
REDIS_HOST = configs.REDIS_HOST
REDIS_PORT = configs.REDIS_PORT

# 环境
env_id = ''

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd6yqlb(u%mxu!t$4evtz@3#5zqo@zy8db09cj1pi2r38^6fi*y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
	'channels',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'login',
	'manager',
	'homepage',
	'corsheaders',
	# 'django_crontab',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'corsheaders.middleware.CorsMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'mymiddleware.Interceptor',

]

# 指定ASGI的路由地址
ASGI_APPLICATION = 'manager.routing.application'

ROOT_URLCONF = 'ME2.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'login/template'), os.path.join(BASE_DIR, 'manager/template'),
		         os.path.join(BASE_DIR, 'homepage/template')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				'login.views.global_setting',
			],
		},
	},
]

WSGI_APPLICATION = 'ME2.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


if configs.dbtype == 'sqlite3':
	DATABASES = {
		'default': {
			'ENGINE': 'django.db.backends.sqlite3',
			'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
			'OPTIONS': {
				'timeout': 20
			}
		}
	}

else:
	DATABASES = {
		'default': {
			'ENGINE': 'django.db.backends.mysql',
			'NAME': configs.DATABASES_NAME,  # 新建数据库名
			'USER': configs.DATABASES_USER,  # 数据库登录名
			'PASSWORD': configs.DATABASES_PWD,  # 数据库登录密码
			'HOST': configs.DATABASES_HOST,  # 数据库所在服务器ip地址
			'PORT': configs.DATABASES_PORT,  # 监听端口 默认3306即可
		}
	}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

###############################

LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'formatters': {
		'verbose': {
			'format': '[%(asctime)s] [%(levelname)s] %(message)s'
		},
	},
	'handlers': {
		'console': {
			'level': 'INFO',
			'class': 'logging.StreamHandler',
			'formatter': 'verbose'
		},
		'file': {
			'level': 'INFO',
			'class': 'logging.FileHandler',
			'filename': './logs/monitor.log',
			'formatter': 'verbose'
		},
		'email': {
			'level': 'ERROR',
			'class': 'django.utils.log.AdminEmailHandler',
			'include_html': True,
		}
	},
	'loggers': {
		'django': {
			'handlers': ['console', 'file', 'email'],
			'level': 'INFO',
			'propagate': True,
		},
	},
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# STATICFILES_DIRS = [
# 	os.path.join(BASE_DIR, "login/static"),
# 	os.path.join(BASE_DIR, 'manager/static'),
# 	os.path.join(BASE_DIR, 'homepage/static'),
# 	os.path.join(BASE_DIR, 'local_reports'),
# 	os.path.join(BASE_DIR, 'PDF.js')
#
# ]

# 配置解决跨域问题
# 跨域增加忽略
CORS_ALLOW_CREDENTIALS = True
# CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = (
	'http://localhost:8000', 'http://127.0.0.1:8000'
)
# ALLOWED_HOSTS = ['*']
CORS_ALLOW_METHODS = (
	'DELETE',
	'GET',
	'OPTIONS',
	'PATCH',
	'POST',
	'PUT',
	'VIEW',
)
CORS_ALLOW_HEADERS = (
	'XMLHttpRequest',
	'X_FILENAME',
	'accept-encoding',
	'authorization',
	'content-type',
	'dnt',
	'origin',
	'user-agent',
	'x-csrftoken',
	'x-requested-with',
)

APPEND_SLASH = False
