# Generated by Django 2.2.3 on 2020-11-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=32)),
                ('childs', models.CharField(blank=True, max_length=256)),
                ('condition', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField(unique=True)),
                ('data', models.TextField(blank=True)),
            ],
        ),
    ]
