from django.urls import path
import homepage.views as views
urlpatterns = [
	path('', views.homepage),
	path('queryproduct/', views.queryproduct),
	path('queryplan/', views.queryplan),
	path('queryallplan/', views.queryallplan),
	path('querytaskid/', views.querytaskid),
	path('globalsetting/', views.globalsetting),
	path('restart/', views.restart),
	path('sendreport/', views.sendreport),
	path('reportchart/', views.reportchart),
	path('badresult/', views.badresult),
	path('plandebug/', views.plandebug),
	path('buglog/', views.querybuglog),
	path('initbugcount/', views.initbugcount),
	path('downloadlog/', views.downloadlog),
	path('jacocoreport/', views.jacocoreport),
	path('queryProductSet/', views.queryProductSet),
	path('editProductSet/', views.editProductSet),
	path('downloadReport/', views.downloadReport),
	path('queryPlanState/', views.queryPlanState),
	path('planforceStop/', views.planforceStop),
	path('query_third_call/', views.query_third_call),
	path('jenkinsJobRun/', views.jenkinsJobRun),
	path('queryProductAndPlan/', views.queryProductAndPlan),
	path('statisticalAnalysis/',views.statisticalAnalysis),
	path('getplandata/',views.getplandata),
	path('getnodes/',views.getnodes),
	path('gettaskidplan/',views.gettaskidplan),
	path('geterrorinfo/',views.geterrorinfo)
]
