# Generated by Django 2.2.3 on 2020-11-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jacoco_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=128)),
                ('jobnum', models.CharField(max_length=32)),
                ('coverydata', models.TextField(blank=True)),
                ('time', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Jenkins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenkinsurl', models.CharField(blank=True, max_length=128, null=True)),
                ('jobname', models.TextField(blank=True, null=True)),
                ('productid', models.CharField(blank=True, max_length=12)),
                ('authname', models.CharField(blank=True, max_length=24, null=True)),
                ('authpwd', models.CharField(blank=True, max_length=24, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('clearjob', models.CharField(blank=True, max_length=128, null=True)),
                ('buildplans', models.TextField(blank=True)),
                ('projectjob', models.TextField(blank=True, null=True)),
                ('gitlaburl', models.CharField(blank=True, max_length=128, null=True)),
                ('gitlabtoken', models.CharField(blank=True, max_length=64, null=True)),
                ('gitpath', models.CharField(blank=True, max_length=64, null=True)),
                ('gitbranch', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
