# Generated by Django 2.2.3 on 2020-02-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jacoco_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenkinsurl', models.CharField(blank=True, max_length=64)),
                ('servicename', models.CharField(blank=True, max_length=32)),
                ('jobname', models.CharField(blank=True, max_length=32)),
                ('productid', models.CharField(blank=True, max_length=12)),
                ('authname', models.CharField(blank=True, max_length=24)),
                ('authpwd', models.CharField(blank=True, max_length=24)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
