# Generated by Django 2.2.3 on 2020-02-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jacoco_report',
            name='authname',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='jacoco_report',
            name='authpwd',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='jacoco_report',
            name='jenkinsurl',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='jacoco_report',
            name='jobname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='jacoco_report',
            name='servicename',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
