# Generated by Django 2.2.3 on 2020-03-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jacoco_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=128)),
                ('jobnum', models.CharField(max_length=32)),
                ('branchCoverage', models.CharField(max_length=32)),
                ('classCoverage', models.CharField(max_length=32)),
                ('complexityScore', models.CharField(max_length=32)),
                ('instructionCoverage', models.CharField(max_length=32)),
                ('lineCoverage', models.CharField(max_length=32)),
                ('methodCoverage', models.CharField(max_length=32)),
            ],
        ),
    ]
