# Generated by Django 2.2.3 on 2020-03-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_jacoco_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jacoco_data',
            name='branchCoverage',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='jacoco_data',
            name='classCoverage',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='jacoco_data',
            name='complexityScore',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='jacoco_data',
            name='instructionCoverage',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='jacoco_data',
            name='lineCoverage',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='jacoco_data',
            name='methodCoverage',
            field=models.CharField(max_length=128),
        ),
    ]
