# Generated by Django 2.2.3 on 2019-10-31 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('headers', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=128)),
                ('content_type', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=10)),
                ('body', models.CharField(max_length=500)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'unique_together': {('url', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=64)),
                ('icon', models.CharField(max_length=64)),
                ('parentid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('run_type', models.CharField(max_length=32)),
                ('last', models.CharField(blank=True, max_length=32)),
                ('is_send_mail', models.CharField(default='close', max_length=6)),
                ('mail_config_id', models.CharField(blank=True, max_length=125)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
                ('cases', models.ManyToManyField(blank=True, to='manager.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('token', 'token')], max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('pick_pattern', models.CharField(max_length=64)),
                ('final_pattern', models.CharField(max_length=64)),
                ('src', models.CharField(max_length=64)),
                ('dest', models.CharField(max_length=64)),
                ('ext', models.CharField(max_length=64)),
                ('ext1', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('tag', models.CharField(blank=True, max_length=64)),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(blank=True, max_length=500)),
                ('gain', models.CharField(blank=True, max_length=500)),
                ('is_cache', models.BooleanField(default=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('interface', '接口'), ('function', '函数')], max_length=12)),
                ('related_id', models.CharField(blank=True, max_length=32)),
                ('description', models.CharField(max_length=500)),
                ('headers', models.CharField(blank=True, max_length=500)),
                ('body', models.CharField(blank=True, max_length=1000)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=128)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('db_check', models.CharField(blank=True, max_length=128)),
                ('itf_check', models.CharField(blank=True, max_length=128)),
                ('temp', models.CharField(blank=True, max_length=128)),
                ('tag_id', models.CharField(blank=True, max_length=32)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='ResultDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=64)),
                ('result', models.CharField(choices=[('success', 'success'), ('fail', 'fail')], max_length=12)),
                ('spend', models.CharField(max_length=64)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Case')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Plan')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Step')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='case', max_length=16)),
                ('related_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_id', models.IntegerField()),
                ('follow_id', models.IntegerField()),
                ('kind', models.CharField(choices=[('plan', '计划'), ('case', '用例')], max_length=16)),
                ('value', models.CharField(blank=True, max_length=64)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='MailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=64)),
                ('to_receive', models.CharField(max_length=125)),
                ('cc_receive', models.CharField(blank=True, max_length=125)),
                ('rich_content', models.CharField(blank=True, max_length=500)),
                ('color_scheme', models.CharField(default='blue', max_length=32)),
                ('is_send_mail', models.CharField(default='close', max_length=125)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceGen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('step', '测试步骤'), ('record', '录制'), ('direct', '直接新增接口')], max_length=16)),
                ('by', models.IntegerField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Interface')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('built-in', '内置'), ('user-defined', '用户定义')], max_length=12)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('flag', models.CharField(max_length=32)),
                ('body', models.CharField(max_length=500)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='DBCon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('oracle', 'Oracle'), ('mysql', 'Mysql'), ('db2', 'DB2')], max_length=10)),
                ('dbname', models.CharField(max_length=15)),
                ('host', models.CharField(blank=True, max_length=15)),
                ('port', models.CharField(blank=True, max_length=5)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=32)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Crontab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
                ('ext', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('close', '关闭'), ('open', '开启')], default='close', max_length=12)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Plan')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='steps',
            field=models.ManyToManyField(blank=True, to='manager.Step'),
        ),
    ]
