# Generated by Django 2.2.3 on 2020-03-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
                ('description', models.TextField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.AlterField(
            model_name='dbcon',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dbcon',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dbcon',
            name='username',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='variable',
            name='tag_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldcode', models.CharField(max_length=16)),
                ('description', models.TextField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('index', models.IntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Template')),
            ],
        ),
    ]
