# Generated by Django 2.2.3 on 2020-01-19 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('businessname', models.TextField()),
                ('itf_check', models.CharField(max_length=128)),
                ('db_check', models.CharField(max_length=128)),
                ('params', models.TextField(blank=True)),
                ('preposition', models.TextField(blank=True)),
                ('postposition', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CommonConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.TextField(blank=True)),
                ('ex_1', models.CharField(blank=True, max_length=64)),
                ('ex_2', models.CharField(blank=True, max_length=64)),
                ('ex_3', models.CharField(blank=True, max_length=64)),
                ('ex_4', models.CharField(blank=True, max_length=64)),
                ('ex_5', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='mailconfig',
            old_name='rich_content',
            new_name='rich_text',
        ),
        migrations.RemoveField(
            model_name='case',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_send_mail',
        ),
        migrations.RemoveField(
            model_name='step',
            name='db_check',
        ),
        migrations.RemoveField(
            model_name='step',
            name='itf_check',
        ),
        migrations.RemoveField(
            model_name='step',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='case',
            name='db_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mailconfig',
            name='dingdingtoken',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailconfig',
            name='is_send_dingding',
            field=models.CharField(default='close', max_length=125),
        ),
        migrations.AddField(
            model_name='mailconfig',
            name='sender_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailconfig',
            name='sender_nick',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailconfig',
            name='sender_pass',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailconfig',
            name='smtp_host',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailconfig',
            name='smtp_port',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='db_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='step',
            name='db_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='function',
            name='kind',
            field=models.CharField(default='用户定义', max_length=12),
        ),
        migrations.AlterField(
            model_name='step',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RemoteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('host', models.CharField(max_length=32)),
                ('port', models.CharField(max_length=6)),
                ('username', models.CharField(blank=True, max_length=32)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='businessdatainfo',
            field=models.ManyToManyField(blank=True, to='manager.BusinessData'),
        ),
        migrations.AddField(
            model_name='resultdetail',
            name='businessdata',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.BusinessData'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='businessdatainfo',
            field=models.ManyToManyField(blank=True, to='manager.BusinessData'),
        ),
    ]
