# Generated by Django 2.2.3 on 2020-01-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200119_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailconfig',
            name='dingdingtoken',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='mailconfig',
            name='sender_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='mailconfig',
            name='sender_nick',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='mailconfig',
            name='sender_pass',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='mailconfig',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='mailconfig',
            name='smtp_port',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='mailconfig',
            name='to_receive',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
