# Generated by Django 2.2.3 on 2020-02-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200120_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='user', max_length=64)),
                ('product_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='variable',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
