# Generated by Django 2.2.3 on 2020-02-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200213_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_running',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
