# Generated by Django 2.2.3 on 2020-02-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_plan_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resultdetail',
            name='is_verify',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='step',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
