# Generated by Django 2.2.3 on 2020-02-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20200218_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdetail',
            name='loop_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
